/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import static Gui.AdminWindow.DATE_FORMAT;
import clinic.DatePicker;
import clinic.Doctor;
import clinic.Employee;
import java.awt.Color;
import static java.awt.Color.white;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author acer
 */
public class EditAccount extends javax.swing.JPanel {

    /**
     * Creates new form EditAccount
     */
    int ID;
    String Role;
    Color col;

    public String getRole() {
        return Role;
    }

    public void setRole(String Role) {
        this.Role = Role;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public EditAccount() {
        initComponents();
        lblSpec.setVisible(false);
        lblChnlFee.setVisible(false);
        lblWPlace.setVisible(false);
        txtSpec.setVisible(false);
        txtWPlace.setVisible(false);
        txtChnlFee.setVisible(false);
        GeneralPanel.setVisible(false);
        UNamePwdPanel.setVisible(false);

        col = lblChange.getBackground();
    }

    public JPanel getGeneralPanel() {
        return GeneralPanel;
    }

    public void setGeneralPanel(JPanel GeneralPanel) {
        this.GeneralPanel = GeneralPanel;
    }

    public JPanel getUNamePwdPanel() {
        return UNamePwdPanel;
    }

    public void setUNamePwdPanel(JPanel UNamePwdPanel) {
        this.UNamePwdPanel = UNamePwdPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        GeneralPanel = new javax.swing.JPanel();
        txtAddress = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        txtSpec = new javax.swing.JTextField();
        txtWPlace = new javax.swing.JTextField();
        txtChnlFee = new javax.swing.JTextField();
        lblWPlace = new javax.swing.JLabel();
        lblSpec = new javax.swing.JLabel();
        lblChnlFee = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblRequired1 = new javax.swing.JLabel();
        lblRequired2 = new javax.swing.JLabel();
        lblRequired3 = new javax.swing.JLabel();
        lblRequired4 = new javax.swing.JLabel();
        lblReqFee = new javax.swing.JLabel();
        UNamePwdPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPPwd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNPwd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNRPwd = new javax.swing.JTextField();
        btnSaveUserD = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtUName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblChange = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        image = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAddress.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel14.setText("First Name     :");

        btnSave.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnSave.setText(" Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel43.setText("Surname         :");

        txtFName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFNameKeyTyped(evt);
            }
        });

        txtLName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLNameKeyTyped(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel44.setText("Date of Birth  :");

        txtDob.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N

        jButton10.setText(" Select");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel45.setText("Address          :");

        txtSpec.setText(" ");
        txtSpec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSpecKeyTyped(evt);
            }
        });

        txtWPlace.setText(" ");
        txtWPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWPlaceActionPerformed(evt);
            }
        });
        txtWPlace.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWPlaceKeyTyped(evt);
            }
        });

        txtChnlFee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChnlFeeKeyTyped(evt);
            }
        });

        lblWPlace.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblWPlace.setText("Working Place         :");

        lblSpec.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblSpec.setText("Specialization          :");

        lblChnlFee.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblChnlFee.setText("Channeling Fee       :");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/Images/acc.jpg"))); // NOI18N

        lblRequired1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRequired1.setForeground(new java.awt.Color(255, 0, 51));
        lblRequired1.setText("*");

        lblRequired2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRequired2.setForeground(new java.awt.Color(255, 0, 51));
        lblRequired2.setText("*");

        lblRequired3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRequired3.setForeground(new java.awt.Color(255, 0, 51));
        lblRequired3.setText("*");

        lblRequired4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRequired4.setForeground(new java.awt.Color(255, 0, 51));
        lblRequired4.setText("*");

        lblReqFee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblReqFee.setForeground(new java.awt.Color(255, 0, 51));
        lblReqFee.setText("*");

        javax.swing.GroupLayout GeneralPanelLayout = new javax.swing.GroupLayout(GeneralPanel);
        GeneralPanel.setLayout(GeneralPanelLayout);
        GeneralPanelLayout.setHorizontalGroup(
            GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPanelLayout.createSequentialGroup()
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GeneralPanelLayout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel43)
                                        .addComponent(jLabel44)
                                        .addComponent(jLabel45))))
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSpec)))
                        .addGap(18, 18, 18)
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addComponent(txtFName, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRequired1))
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addComponent(txtDob, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRequired3)
                                .addGap(123, 123, 123))
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRequired4))
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addComponent(txtSpec, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                                .addGap(15, 15, 15))
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addComponent(txtLName, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRequired2)))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblChnlFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblWPlace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtChnlFee, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                                    .addComponent(txtWPlace, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReqFee)
                        .addGap(69, 69, 69)))
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addGap(208, 208, 208))
        );
        GeneralPanelLayout.setVerticalGroup(
            GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPanelLayout.createSequentialGroup()
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRequired1))
                                .addGap(18, 18, 18)
                                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel43)
                                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRequired2))
                                .addGap(18, 18, 18)
                                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel44)
                                        .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblRequired3)))
                                .addGap(29, 29, 29)
                                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRequired4)))
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(jLabel45)))
                        .addGap(7, 7, 7)
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSpec, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSpec))
                        .addGap(13, 13, 13)
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWPlace))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtChnlFee, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblChnlFee))
                            .addComponent(lblReqFee)))
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jLayeredPane1.add(GeneralPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 480));

        jPanel1.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel10.setText("Enter Previous Password  :");

        txtPPwd.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        txtPPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPPwdKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel6.setText(" Change password");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel11.setText("Enter New Password         :");

        txtNPwd.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        txtNPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNPwdKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel12.setText("Re-enter New Password   :");

        txtNRPwd.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        txtNRPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNRPwdKeyTyped(evt);
            }
        });

        btnSaveUserD.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnSaveUserD.setText(" Save");
        btnSaveUserD.setToolTipText("");
        btnSaveUserD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUserDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSaveUserD)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(20, 20, 20))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPPwd)
                                .addGap(1, 1, 1))
                            .addComponent(txtNRPwd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNPwd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNRPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveUserD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel9.setText(" User Name                         :");

        txtUName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        txtUName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUNameKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel7.setText("Change User Name");

        lblChange.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblChange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChange.setText(" Change");
        lblChange.setOpaque(true);
        lblChange.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblChangeMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblChangeMouseMoved(evt);
            }
        });
        lblChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblChangeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblChangeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblChangeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblChangeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUName, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblChange)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/Images/pass.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout UNamePwdPanelLayout = new javax.swing.GroupLayout(UNamePwdPanel);
        UNamePwdPanel.setLayout(UNamePwdPanelLayout);
        UNamePwdPanelLayout.setHorizontalGroup(
            UNamePwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UNamePwdPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(UNamePwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UNamePwdPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        UNamePwdPanelLayout.setVerticalGroup(
            UNamePwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UNamePwdPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLayeredPane1.add(UNamePwdPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, 1730, 480));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/Images/details.png"))); // NOI18N

        javax.swing.GroupLayout imageLayout = new javax.swing.GroupLayout(image);
        image.setLayout(imageLayout);
        imageLayout.setHorizontalGroup(
            imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imageLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel3)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        imageLayout.setVerticalGroup(
            imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, Short.MAX_VALUE)
        );

        jLayeredPane1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 480));

        jLabel4.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" General Settings");
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 153, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Change User Name And Password");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        jLabel31.setBackground(new java.awt.Color(153, 204, 255));
        jLabel31.setOpaque(true);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/Images/clinic logo.png"))); // NOI18N
        jLabel30.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    final static String DATE_FORMAT = "yyyy-MM-dd";

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int Id = ID;
        if (!txtFName.getText().equals("") && !txtLName.getText().equals("") && !txtDob.getText().equals("") && !txtAddress.getText().equals("")) {
            String FName = txtFName.getText();
            String LName = txtLName.getText();
            String DOB = txtDob.getText();

            boolean date = false;
            //date format
            try {
                DateFormat df = new SimpleDateFormat(DATE_FORMAT);
                df.setLenient(false);
                df.parse(txtDob.getText());
                date = true;
            } catch (ParseException e) {
                date = false;
            }

            //age
            Date userdate = null;
            Date today = null;

            try {
                userdate = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(txtDob.getText());
            } catch (ParseException ex) {
                Logger.getLogger(ReceptionistWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                today = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(String.valueOf(java.time.LocalDate.now()));
            } catch (ParseException ex) {
                Logger.getLogger(ReceptionistWindow.class.getName()).log(Level.SEVERE, null, ex);
            }

            Calendar gc1 = new GregorianCalendar();

            gc1.setTime(today);
            Calendar gc2 = new GregorianCalendar();
            gc2.setTime(userdate);
            long daysdiff = (gc1.getTimeInMillis() - gc2.getTimeInMillis()) / (1000 * 3600 * 24);

            String Address = txtAddress.getText();
            if (date == true && daysdiff > 0) {
                if (Role.equals("D")) {
                    if (!txtChnlFee.getText().equals("")) {
                        String Spec = txtSpec.getText();
                        String WPlace = txtWPlace.getText();
                        float ChnFee = Float.parseFloat(txtChnlFee.getText());
                        Doctor d = new Doctor(Id, FName, LName, DOB, Address, Spec, WPlace, ChnFee);
                        d.changeAccount(d);
                    } else {
                        JOptionPane.showMessageDialog(null, "Fill All the required Fields!!");
                    }
                } else if (Role.equals("R") || Role.equals("A")) {
                    Employee e = new Employee(Id, FName, LName, Address, DOB);
                    e.changeAccount(e);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Invalid date!!");

            }
        } else {
            JOptionPane.showMessageDialog(null, "Fill All the required Fields!!");
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        SetData();
    }//GEN-LAST:event_jLabel4MousePressed

    void SetData() {
        GeneralPanel.setVisible(true);
        UNamePwdPanel.setVisible(false);
        if (Role.equals("D")) {
            lblSpec.setVisible(true);
            lblChnlFee.setVisible(true);
            lblWPlace.setVisible(true);
            txtSpec.setVisible(true);
            txtWPlace.setVisible(true);
            txtChnlFee.setVisible(true);
            Doctor d = new Doctor();
            d.setId(ID);
            Employee e = new Employee();
            e.setId(ID);
            try {
                e.ViewAccount(e);
                d.ViewAccount(d);
            } catch (IOException ex) {
                Logger.getLogger(EditAccount.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(EditAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtFName.setText(e.getFname());
            txtLName.setText(e.getLname());
            txtDob.setText(e.getDOB());
            txtAddress.setText(e.getAddress());
            txtSpec.setText(d.getSpecialization());
            txtWPlace.setText(d.getWplace());
            txtChnlFee.setText(String.valueOf(d.getChnFee()));
        } else if (Role.equals("R") || Role.equals("A")) {
            lblReqFee.setVisible(false);
            Employee d = new Employee();
            d.setId(ID);
            try {
                d.ViewAccount(d);
            } catch (IOException ex) {
                Logger.getLogger(EditAccount.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(EditAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtFName.setText(d.getFname());
            txtLName.setText(d.getLname());
            txtDob.setText(d.getDOB());
            txtAddress.setText(d.getAddress());
            txtSpec.enableInputMethods(false);
            txtWPlace.enableInputMethods(false);
            txtChnlFee.enableInputMethods(false);
        }
    }

    Employee d = new Employee();
    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        txtUName.setEditable(false);
        UNamePwdPanel.setVisible(true);
        GeneralPanel.setVisible(false);
        d.setId(ID);
        d.ViewUserInfro(d);
        txtUName.setText(d.getUsername());
    }//GEN-LAST:event_jLabel5MousePressed

    private void btnSaveUserDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUserDActionPerformed
        if (!txtPPwd.getText().equals("") && !txtNPwd.getText().equals("") && !txtNRPwd.getText().equals("") && !txtUName.getText().equals("")) {
            if (!txtPPwd.getText().equals(d.getPassword())) {
                JOptionPane.showMessageDialog(null, "Incorrect Previous Password");
                clear();
            } else {
                if (!txtNPwd.getText().equals(txtNRPwd.getText())) {
                    JOptionPane.showMessageDialog(null, "Re-type password Not Match");
                    clear();
                } else {
                    d.setUsername(txtUName.getText());
                    d.setPassword(txtNPwd.getText());
                    d.ChangeUserDeatials(d);
                    txtUName.setEditable(false);
                    JOptionPane.showMessageDialog(null, "New username and new password successfully saved!");
                }
            }
        } else {
            if (!txtUName.getText().equals("")) {
                d.setUsername(txtUName.getText());
                //d.setPassword(txtNPwd.getText());
                d.ChangeUserDeatials(d);
                txtUName.setEditable(false);
                JOptionPane.showMessageDialog(null, "New username successfully saved!");
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Username");
            }
        }
    }//GEN-LAST:event_btnSaveUserDActionPerformed

    private void lblChangeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeMousePressed
        txtUName.setEditable(true);
    }//GEN-LAST:event_lblChangeMousePressed

    private void txtWPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWPlaceActionPerformed

    private void lblChangeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblChangeMouseDragged

    private void lblChangeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeMouseMoved
        // TODO add your handling code here:


    }//GEN-LAST:event_lblChangeMouseMoved

    private void lblChangeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeMouseEntered
        // TODO add your handling code here:

        lblChange.setBackground(white);
    }//GEN-LAST:event_lblChangeMouseEntered

    private void lblChangeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_lblChangeMouseReleased

    private void lblChangeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeMouseExited
        // TODO add your handling code here:

        lblChange.setBackground(col);
    }//GEN-LAST:event_lblChangeMouseExited

    private void txtFNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFNameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFNameKeyTyped

    private void txtLNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtLNameKeyTyped

    private void txtSpecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpecKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || c == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSpecKeyTyped

    private void txtWPlaceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWPlaceKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || c == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtWPlaceKeyTyped

    private void txtChnlFeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChnlFeeKeyTyped
        // TODO add your handling code here:
        char k = evt.getKeyChar();
        if (!(k >= '0' && k <= '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtChnlFeeKeyTyped

    private void txtUNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUNameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtUNameKeyTyped

    private void txtPPwdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPPwdKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPPwdKeyTyped

    private void txtNPwdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNPwdKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNPwdKeyTyped

    private void txtNRPwdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNRPwdKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNRPwdKeyTyped
    public void clear() {
        txtPPwd.setText("");
        txtNPwd.setText("");
        txtNRPwd.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GeneralPanel;
    private javax.swing.JPanel UNamePwdPanel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveUserD;
    private javax.swing.JPanel image;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblChnlFee;
    private javax.swing.JLabel lblReqFee;
    private javax.swing.JLabel lblRequired1;
    private javax.swing.JLabel lblRequired2;
    private javax.swing.JLabel lblRequired3;
    private javax.swing.JLabel lblRequired4;
    private javax.swing.JLabel lblSpec;
    private javax.swing.JLabel lblWPlace;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtChnlFee;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtNPwd;
    private javax.swing.JTextField txtNRPwd;
    private javax.swing.JTextField txtPPwd;
    private javax.swing.JTextField txtSpec;
    private javax.swing.JTextField txtUName;
    private javax.swing.JTextField txtWPlace;
    // End of variables declaration//GEN-END:variables
}
